name: IndexNow 추가

on:
  repository_dispatch:
    types:
      - indexnow-add  # "indexnow-add" 이벤트 타입 감지

jobs:
  indexnow_add_job:
    runs-on: ubuntu-latest

    steps:
      - name: 30초 대기
        run: |
          echo "IndexNow 워크플로우 시작 후 30초 대기합니다..."
          sleep 30
          
      - name: 추가된 파일 출력
        run: |
          echo "IndexNow 추가 워크플로우가 실행되었습니다."

          # 전달된 client_payload 전체를 출력해봅니다.
          echo "전달된 client_payload 데이터: ${{ toJson(github.event.client_payload) }}"

          # 전달된 추가된 파일 목록을 쉼표로 분리된 배열로 가져옵니다.
          ADDED_FILES="${{ join(github.event.client_payload.added_files, ',') }}"
          echo "전달된 추가된 파일 목록: $ADDED_FILES"

          # 파일 목록을 쉼표를 기준으로 나누어 하나씩 출력
          IFS=',' read -ra FILES <<< "$ADDED_FILES"
          for FILE in "${FILES[@]}"; do
            echo "추가된 파일: $FILE"
          done

      - name: 파일명에서 제목 추출 및 개별 URL IndexNow API 호출
        env:
          INDEXNOW_API_KEY: ${{ secrets.INDEXNOW_API_KEY }}
        run: |
          set +e  # 오류 발생 시 스크립트가 중단되지 않도록 설정
          
          ADDED_FILES="${{ join(github.event.client_payload.added_files, ',') }}"
          echo "전달된 추가된 파일 목록: $ADDED_FILES"

          # 파일 목록을 쉼표를 기준으로 나누어 하나씩 처리하여 URL 구성
          IFS=',' read -ra FILES <<< "$ADDED_FILES"
          
          for FILE in "${FILES[@]}"; do
            # 파일명에서 날짜와 확장자를 제외한 제목 부분만 추출
            TITLE=$(echo "$FILE" | sed -E 's|_posts/[0-9]{4}-[0-9]{2}-[0-9]{2}-(.*)\.md|\1|')
            echo "추출된 제목: $TITLE"

            # URL 구성 (추출된 제목을 기반으로 페이지 URL 생성)
            URL="https://leejuhyeong424dev.github.io/posts/${TITLE}"
            
            # IndexNow API 호출을 위한 JSON 데이터 구성
            JSON_PAYLOAD="{\"host\": \"leejuhyeong424dev.github.io\", \"key\": \"$INDEXNOW_API_KEY\", \"keyLocation\": \"https://leejuhyeong424dev.github.io/myIndexNowKey.txt\", \"urlList\": [\"${URL}\"]}"
            
            echo "IndexNow API 호출 중... JSON Payload: $JSON_PAYLOAD"

            # IndexNow API 호출 및 응답 저장
            RESPONSE=$(curl -s -X POST "https://api.indexnow.org/indexnow" \
              -H "Content-Type: application/json" \
              -d "$JSON_PAYLOAD" -w "\n%{http_code}" || true)

            # 응답 본문과 상태 코드 분리
            HTTP_BODY=$(echo "$RESPONSE" | sed '$d')
            HTTP_STATUS=$(echo "$RESPONSE" | tail -n1)

            # 응답 출력 및 상태 코드 확인
            echo "IndexNow API 응답 본문 (URL: $URL):"
            echo "$HTTP_BODY"
            echo "IndexNow API 상태 코드 (URL: $HTTP_STATUS)"
          done
